# Happiness Predictor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model

In [2]:
df = pd.read_pickle('happiness_data.pkl')
df

Country  Year  Score   Economy    Family    Health  \
0             Afghanistan  2015  3.575  0.319820  0.302850  0.303350   
1             Afghanistan  2016  3.360  0.382270  0.110370  0.173440   
2             Afghanistan  2017  3.794  0.401477  0.581543  0.180747   
3                 Albania  2015  4.959  0.878670  0.804340  0.813250   
4                 Albania  2016  4.655  0.955300  0.501630  0.730070   
5                 Albania  2017  4.644  0.996193  0.803685  0.731160   
6                 Algeria  2015  5.605  0.939290  1.077720  0.617660   
7                 Algeria  2016  6.355  1.052660  0.833090  0.618040   
8                 Algeria  2017  5.872  1.091864  1.146217  0.617585   
9                  Angola  2015  4.033  0.757780  0.860400  0.166830   
10                 Angola  2016  3.866  0.847310  0.663660  0.049910   
11                 Angola  2017  3.795  0.858428  1.104412  0.049869   
12              Argentina  2015  6.574  1.053510  1.248230  0.787230   
13              Argentina  2016  6.650  1.151370  1.066120  0.697110   
14              Argentina  2017  6.599  1.185295  1.440451  0.695137   
15                Armenia  2015  4.350  0.768210  0.777110  0.729900   
16                Armenia  2016  4.360  0.860860  0.624770  0.640830   
17                Armenia  2017  4.376  0.900597  1.007484  0.637524   
18              Australia  2015  7.284  1.333580  1.309230  0.931560   
19              Australia  2016  7.313  1.444430  1.104760  0.851200   
20              Australia  2017  7.284  1.484415  1.510042  0.843887   
21                Austria  2015  7.200  1.337230  1.297040  0.890420   
22                Austria  2016  7.119  1.450380  1.083830  0.805650   
23                Austria  2017  7.006  1.487097  1.459945  0.815328   
24             Azerbaijan  2015  5.212  1.023890  0.937930  0.640450   
25             Azerbaijan  2016  5.291  1.123730  0.760420  0.545040   
26             Azerbaijan  2017  5.234  1.153602  1.152400  0.540776   
27                Bahrain  2015  5.960  1.323760  1.216240  0.747160   
28                Bahrain  2016  6.218  1.440240  0.943970  0.656960   
29                Bahrain  2017  6.087  1.488412  1.323110  0.653133   
..                    ...   ...    ...       ...       ...       ...   
363                Uganda  2015  3.931  0.211020  1.132990  0.338610   
364                Uganda  2016  3.739  0.347190  0.909810  0.196250   
365                Uganda  2017  4.081  0.381431  1.129828  0.217633   
366               Ukraine  2015  4.681  0.799070  1.202780  0.673900   
367               Ukraine  2016  4.324  0.872870  1.014130  0.586280   
368               Ukraine  2017  4.096  0.894652  1.394538  0.575904   
369  United Arab Emirates  2015  6.901  1.427270  1.125750  0.809250   
370  United Arab Emirates  2016  6.573  1.573520  0.871140  0.729930   
371  United Arab Emirates  2017  6.648  1.626343  1.266410  0.726798   
372        United Kingdom  2015  6.867  1.266370  1.285480  0.909430   
373        United Kingdom  2016  6.725  1.402830  1.086720  0.809910   
374        United Kingdom  2017  6.714  1.441634  1.496460  0.805336   
375         United States  2015  7.119  1.394510  1.247110  0.861790   
376         United States  2016  7.104  1.507960  1.047820  0.779000   
377         United States  2017  6.993  1.546259  1.419921  0.774287   
378               Uruguay  2015  6.485  1.061660  1.208900  0.811600   
379               Uruguay  2016  6.545  1.181570  1.031430  0.721830   
380               Uruguay  2017  6.454  1.217560  1.412228  0.719217   
381            Uzbekistan  2015  6.003  0.632440  1.340430  0.597720   
382            Uzbekistan  2016  5.987  0.735910  1.168100  0.501630   
383            Uzbekistan  2017  5.971  0.786441  1.548969  0.498273   
384               Vietnam  2015  5.360  0.632160  0.912260  0.746760   
385               Vietnam  2016  5.061  0.740370  0.791170  0.661570   
386               Vietnam  2017  5.074  0.788548  1.277491

In [3]:
years_train = [2015,2016]
years_test = [2017]
train_features = df.loc[df['Year'].isin(years_train)]
test_features = df.loc[df['Year'].isin(years_test)]
train_features.reset_index(inplace=True,drop=True)
test_features.reset_index(inplace=True,drop=True)
train_features

Country  Year  Score  Economy   Family   Health  Freedom  \
0             Afghanistan  2015  3.575  0.31982  0.30285  0.30335  0.23414   
1             Afghanistan  2016  3.360  0.38227  0.11037  0.17344  0.16430   
2                 Albania  2015  4.959  0.87867  0.80434  0.81325  0.35733   
3                 Albania  2016  4.655  0.95530  0.50163  0.73007  0.31866   
4                 Algeria  2015  5.605  0.93929  1.07772  0.61766  0.28579   
5                 Algeria  2016  6.355  1.05266  0.83309  0.61804  0.21006   
6                  Angola  2015  4.033  0.75778  0.86040  0.16683  0.10384   
7                  Angola  2016  3.866  0.84731  0.66366  0.04991  0.00589   
8               Argentina  2015  6.574  1.05351  1.24823  0.78723  0.44974   
9               Argentina  2016  6.650  1.15137  1.06612  0.69711  0.42284   
10                Armenia  2015  4.350  0.76821  0.77711  0.72990  0.19847   
11                Armenia  2016  4.360  0.86086  0.62477  0.64083  0.14037   
12              Australia  2015  7.284  1.33358  1.30923  0.93156  0.65124   
13              Australia  2016  7.313  1.44443  1.10476  0.85120  0.56837   
14                Austria  2015  7.200  1.33723  1.29704  0.89042  0.62433   
15                Austria  2016  7.119  1.45038  1.08383  0.80565  0.54355   
16             Azerbaijan  2015  5.212  1.02389  0.93793  0.64045  0.37030   
17             Azerbaijan  2016  5.291  1.12373  0.76042  0.54504  0.35327   
18                Bahrain  2015  5.960  1.32376  1.21624  0.74716  0.45492   
19                Bahrain  2016  6.218  1.44024  0.94397  0.65696  0.47375   
20             Bangladesh  2015  4.694  0.39753  0.43106  0.60164  0.40820   
21             Bangladesh  2016  4.643  0.54177  0.24749  0.52989  0.39778   
22                Belarus  2015  5.813  1.03192  1.23289  0.73608  0.37938   
23                Belarus  2016  5.802  1.13062  1.04993  0.63104  0.29091   
24                Belgium  2015  6.937  1.30782  1.28566  0.89667  0.58450   
25                Belgium  2016  6.929  1.42539  1.05249  0.81959  0.51354   
26                  Benin  2015  3.340  0.28665  0.35386  0.31910  0.48450   
27                  Benin  2016  3.484  0.39499  0.10419  0.21028  0.39747   
28                 Bhutan  2015  5.253  0.77042  1.10395  0.57407  0.53206   
29                 Bhutan  2016  5.196  0.85270  0.90836  0.49759  0.46074   
..                    ...   ...    ...      ...      ...      ...      ...   
232                  Togo  2015  2.839  0.20868  0.13995  0.28443  0.36453   
233                  Togo  2016  3.303  0.28123  0.00100  0.24811  0.34678   
234   Trinidad and Tobago  2015  6.168  1.21183  1.18354  0.61483  0.55884   
235   Trinidad and Tobago  2016  6.168  1.32572  0.98569  0.52608  0.48453   
236               Tunisia  2015  4.739  0.88113  0.60429  0.73793  0.26268   
237               Tunisia  2016  5.045  0.97724  0.43165  0.59577  0.23553   
238                Turkey  2015  5.332  1.06098  0.94632  0.73172  0.22815   
239                Turkey  2016  5.389  1.16492  0.87717  0.64718  0.23889   
240          Turkmenistan  2015  5.548  0.95847  1.22668  0.53886  0.47610   
241          Turkmenistan  2016  5.658  1.08017  1.03817  0.44006  0.37408   
242                Uganda  2015  3.931  0.21102  1.13299  0.33861  0.45727   
243                Uganda  2016  3.739  0.34719  0.90981  0.19625  0.43653   
244               Ukraine  2015  4.681  0.79907  1.20278  0.67390  0.25123   
245               Ukraine  2016  4.324  0.87287  1.01413  0.58628  0.12859   
246  United Arab Emirates  2015  6.901  1.42727  1.12575  0.80925  0.64157   
247  United Arab Emirates  2016  6.573  1.57352  0.87114  0.72993  0.56215   
248        United Kingdom  2015  6.867  1.26637  1.28548  0.90943  0.59625   
249        United Kingdom  2016  6.725  1.40283  1.08672  0.80991  0.50036   
250         United States  2015  7.119  1.39451  1.24711  0.86179  0.54604   
251         United States  2016  7.104  

In [4]:
df_train = train_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)
df_test = test_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)
df_train

Ind 1      Ind 2      Ind 3      Ind 4     Ind 5      Ind 6  \
0     71.500000  95.596610   4.618468   4.923567  2.643742 -10.288447   
1     84.137138  95.596610   4.618468   4.923567  2.643742 -10.879392   
2    100.000000  95.596610   4.618468   4.923567  3.227285  15.802049   
3    100.000000  95.658550   3.196611   3.361734  3.227285  16.646368   
4     99.336708  99.267100  -2.760442  -4.609593  4.467196  36.803859   
5     99.439568  99.231210  -4.133982  -5.868105  4.467196  35.528237   
6     42.000000  99.515772  10.484883   6.761621  3.570000  -0.451391   
7     40.520607  99.588615   2.615014  -0.783083  3.570000   3.061931   
8     99.995209  99.734300   2.193567   1.166753  5.057314  14.603558   
9    100.000000  99.341520  -2.172171  -3.130795  5.057314  13.961236   
10   100.000000  92.809330  -2.106390  -2.466492  2.700193  17.426764   
11   100.000000  92.327590  -2.182668  -2.445738  2.700193  15.864174   
12   100.000000  97.120100   1.401755  -0.072012  4.917263  23.602431   
13   100.000000  96.783000   0.536793  -0.958232  4.917263  21.906456   
14   100.000000  95.774900   0.862118  -0.262225  5.218720  25.671325   
15   100.000000  95.270850   2.113296   1.014996  5.218720  26.025874   
16   100.000000  94.262750   4.551232   2.773520  2.607015  28.591094   
17   100.000000  94.965290   5.770199   3.652782  2.607015  22.817417   
18   100.000000  97.995440   8.208135   5.411306  2.910000  27.231161   
19   100.000000  97.900260   1.934934  -1.878477  2.910000  29.438032   
20    68.204681  97.624413   6.054345   4.873012  1.738671  33.851776   
21    75.920000  96.386817   6.531618   5.387093  1.653366  35.099968   
22   100.000000  94.636060  -6.807324  -6.955662  4.926416  26.903089   
23   100.000000  96.425550 -15.686528 -15.792284  4.926416  22.805946   
24   100.000000  98.380750   1.204604   0.619873  6.222160  23.188446   
25   100.000000  98.662190   2.368947   1.851963  6.222160  23.853864   
26    40.033478  97.847925   1.554765  -1.222640  4.010592  15.849535   
27    41.402615  97.440793  -0.265889  -2.984340  4.010592  21.081754   
28    98.423523  84.619480   3.354964   1.919205  6.945663  22.563659   
29   100.000000  82.995470   6.413242   5.028795  6.945663  33.197121   
..          ...        ...        ...        ...       ...        ...   
232   45.028545  96.570750  10.218804   7.426673  5.602628  -6.737533   
233   46.928375  91.074420   2.856510   0.293039  5.602628   0.604337   
234  100.000000  92.120721   3.736717   1.392512  2.870000  15.288076   
235  100.000000  92.596083   4.176821   1.942249  2.870000  13.930762   
236  100.000000  93.546806   5.057029   3.041722  5.900000  11.216135   
237  100.000000  94.022167   5.497133   3.591459  5.900000   9.405494   
238  100.000000  94.972890   6.377340   4.690932  4.292377  25.081572   
239  100.000000  94.440430   3.370172   1.756869  4.292377  24.750633   
240  100.000000  94.718697   3.935441   1.598151  2.320000  21.867116   
241  100.000000  94.857831   4.218075   1.518792  2.320000  20.425358   
242   18.500000  95.136098   4.783343   1.360074  1.980319  17.541841   
243   26.700000  95.275232  -3.310473  -6.440615  1.980319  20.204879   
244  100.000000  95.553499 -10.268497  -9.373517  5.801227  15.907884   
245  100.000000  95.692633   3.858878   2.336341  5.801227  17.624340   
246  100.000000  95.970900  -8.358350  -9.193599  5.745038  15.417920   
247  100.000000  97.178650  -2.636028  -3.847194  5.716943  14.314710   
248  100.000000  99.941970   2.915722   2.100819  5.660753  12.108289   
249  100.000000  99.763440   2.303555   1.575679  5.660753  11.609867   
250  100.000000  94.600230   3.870160   3.088055  4.784507  18.959920   
251  100.000000  95.892060   0.974144   0.235399  4.784507  17.765126   
252   99.709480  97.697720   0.034012  -0.315978  4.301524  17.344621   
253  100.000000  98.345960   1.563743   1.196475  4.301524  18.212546   
254  100.000000  97.124970   4.207373   2.405487  9.374764  22.45398

In [5]:
#fetching training and test data set

economy_train = pd.DataFrame(train_features['Economy'])
family_train = pd.DataFrame(train_features['Family'])
health_train = pd.DataFrame(train_features['Health'])
freedom_train = pd.DataFrame(train_features['Freedom'])
trust_train = pd.DataFrame(train_features['Trust'])
generosity_train = pd.DataFrame(train_features['Generosity'])
dystopia_train = pd.DataFrame(train_features['Dystopia'])

economy_test = pd.DataFrame(train_features['Economy'])
family_test = pd.DataFrame(train_features['Family'])
health_test = pd.DataFrame(train_features['Health'])
freedom_test = pd.DataFrame(train_features['Freedom'])
trust_test = pd.DataFrame(train_features['Trust'])
generosity_test = pd.DataFrame(train_features['Generosity'])
dystopia_test = pd.DataFrame(train_features['Dystopia'])

In [6]:
# training the model to predict economy

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(economy_train, economy_train.values.ravel())
predictions = rf.predict(economy_test)
errors = abs(predictions - economy_test.values.ravel())
mape = 100 * (errors / economy_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  99.44095635649816
Mean Absolute Error: 0.0 degrees


array([4.40193571e-05, 2.81034407e-03, 5.63100000e-05, 4.38799143e-04,
       7.45666666e-06, 1.00419857e-03, 1.84140000e-04, 1.03420000e-04,
       5.56458571e-04, 3.12817536e-04, 2.72650000e-04, 7.12950000e-04,
       7.32640000e-05, 5.13314000e-04, 1.13294881e-05, 1.44720000e-04,
       2.47034024e-04, 1.66107667e-04, 7.60740286e-04, 3.67716250e-04,
       1.10789400e-03, 1.45541400e-03, 4.23475000e-04, 6.31879500e-04,
       1.10820000e-04, 1.05609233e-03, 7.37919333e-04, 4.38966000e-04,
       1.63173000e-03, 3.91300000e-04, 2.86069750e-03, 2.30766000e-03,
       6.72249048e-04, 1.42314476e-04, 5.31549667e-04, 1.76548000e-03,
       6.18590000e-04, 6.34500000e-05, 1.62150071e-04, 1.97220238e-04,
       1.90100000e-03, 1.74019357e-04, 7.44482933e-03, 1.40684000e-03,
       4.36782000e-04, 5.04498600e-03, 1.64040529e-03, 1.46670000e-04,
       2.49672917e-04, 4.57716250e-04, 7.90194643e-05, 1.68240529e-03,
       2.11843500e-03, 5.85222500e-04, 9.99623333e-04, 1.26596917e-04,
      

In [7]:
# training the model to predict family

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(family_train, family_train.values.ravel())
predictions = rf.predict(family_test)
errors = abs(predictions - family_test.values.ravel())
mape = 100 * (errors / family_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  84.50326812867758
Mean Absolute Error: 0.0 degrees


array([1.59148000e-03, 4.06748000e-03, 3.57908500e-04, 1.85540000e-04,
       8.67996667e-04, 2.96566667e-05, 5.08760000e-05, 4.73900000e-05,
       5.49880000e-04, 3.88150000e-04, 4.90675143e-04, 6.35176310e-04,
       1.17704000e-03, 1.64573179e-04, 1.02269000e-03, 4.26988667e-04,
       1.83556738e-03, 7.92924405e-05, 2.97030000e-04, 8.24188809e-05,
       1.28667488e-03, 5.66150000e-04, 4.00707333e-04, 2.37350000e-04,
       9.00510714e-05, 1.39230000e-04, 8.87547800e-03, 7.83728000e-03,
       2.87984821e-04, 1.31975000e-05, 5.28808000e-04, 4.41800000e-04,
       1.08228000e-03, 1.34886667e-04, 4.45731786e-05, 2.80370667e-04,
       3.80707333e-04, 2.00946952e-04, 5.55554821e-04, 1.00637000e-03,
       5.83894619e-04, 1.67216833e-04, 4.58704000e-04, 6.02365000e-03,
       9.17966667e-06, 1.06195267e-02, 4.94581667e-05, 1.07376310e-04,
       8.92790000e-04, 8.20106429e-05, 1.20707560e-04, 7.86223500e-04,
       2.48650000e-04, 2.49944940e-04, 4.69158861e-04, 4.71290000e-04,
      

In [8]:
# training the model to predict health

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(health_train, health_train.values.ravel())
predictions = rf.predict(health_test)
errors = abs(predictions - health_test.values.ravel())
mape = 100 * (errors / health_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  95.5668904317313
Mean Absolute Error: 0.0 degrees


array([1.00822605e-03, 2.13607000e-03, 6.84899892e-05, 9.10435180e-05,
       3.50566810e-04, 2.94331905e-05, 5.11872500e-04, 9.50270000e-04,
       7.35356429e-04, 3.17963607e-04, 7.89564820e-05, 2.72194567e-04,
       1.46867000e-03, 4.72192381e-04, 5.65400000e-05, 7.90340000e-05,
       6.55902897e-05, 1.68509671e-03, 4.03349405e-04, 1.16653586e-03,
       6.11641667e-05, 3.00126833e-04, 3.58518056e-05, 2.50924190e-04,
       8.61620000e-04, 6.80319679e-04, 4.08469286e-04, 6.42300000e-04,
       9.80059167e-05, 6.20840000e-04, 1.97842619e-05, 2.53474714e-04,
       2.20192381e-05, 3.46601718e-04, 1.79390000e-04, 5.19370000e-04,
       2.27963607e-04, 7.68655238e-05, 3.72391667e-05, 4.50038643e-04,
       1.51702000e-03, 6.90790000e-04, 1.12958000e-03, 9.37808786e-04,
       4.36573333e-05, 1.79184500e-03, 2.93930000e-04, 9.55090600e-03,
       1.16992000e-03, 6.73093500e-04, 2.84243500e-03, 3.32447000e-03,
       6.39425000e-04, 2.32679679e-04, 6.20820811e-04, 4.34148194e-04,
      

In [9]:
# training the model to predict freedom

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(freedom_train, freedom_train.values.ravel())
predictions = rf.predict(freedom_test)
errors = abs(predictions - freedom_test.values.ravel())
mape = 100 * (errors / freedom_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  98.05548940358895
Mean Absolute Error: 0.0 degrees


array([5.46669667e-04, 3.26419000e-03, 6.15014286e-04, 2.19257429e-04,
       5.44820190e-04, 4.58380000e-04, 1.56348667e-03, 1.20500000e-04,
       6.16010476e-05, 3.16271048e-04, 2.86563000e-04, 3.98970000e-04,
       2.73070000e-04, 4.05519464e-04, 3.94975500e-04, 7.06310137e-06,
       1.81325000e-05, 9.87432143e-05, 4.53840000e-04, 1.51279000e-04,
       6.26112341e-05, 6.26405079e-05, 1.43976286e-04, 2.97132000e-04,
       1.67625000e-05, 5.89686000e-04, 5.30326071e-05, 1.84779492e-04,
       2.87004667e-04, 1.39988667e-04, 4.37976190e-05, 1.71700000e-04,
       1.27813000e-03, 2.46050000e-04, 2.59025905e-04, 1.46050000e-05,
       4.11420667e-04, 7.72108333e-05, 7.18323333e-04, 1.98120000e-04,
       4.80427433e-04, 7.92027143e-04, 1.10466119e-03, 4.75355000e-03,
       4.22200000e-04, 5.79440000e-04, 6.45970381e-04, 3.58750737e-04,
       7.32716667e-05, 9.65641190e-05, 3.00319317e-04, 1.80020190e-04,
       4.44605000e-04, 2.26397619e-04, 4.96632286e-04, 8.48316190e-05,
      

In [10]:
# training the model to predict trust

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(trust_train, trust_train.values.ravel())
predictions = rf.predict(trust_test)
errors = abs(predictions - trust_test.values.ravel())
#print('Ravel: ',trust_test.values.ravel())
mape = 100 * (errors / trust_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  99.36683618782223
Mean Absolute Error: 0.0 degrees


array([7.68073675e-04, 1.11873571e-04, 5.88393651e-05, 2.14564112e-04,
       3.62739516e-04, 8.44119643e-05, 1.09534798e-04, 1.96470569e-05,
       1.65361889e-04, 2.40185615e-04, 3.39123762e-04, 2.96248476e-04,
       1.60020000e-05, 2.15900000e-05, 1.78844000e-04, 4.82087460e-05,
       2.66947750e-04, 1.39282810e-04, 4.58938000e-04, 7.61000000e-05,
       1.04171687e-04, 2.44171687e-04, 3.27170833e-04, 8.88442540e-05,
       1.23301676e-03, 1.31060000e-03, 7.03654286e-05, 4.30869048e-06,
       2.38523500e-04, 1.14411964e-04, 2.08450893e-04, 2.20068452e-05,
       1.33469095e-04, 2.85709095e-04, 7.73041706e-05, 3.83145794e-04,
       9.58130953e-06, 2.48293651e-05, 3.39479667e-04, 3.37938865e-04,
       8.97861429e-05, 2.04485980e-04, 9.93415238e-05, 5.68865873e-05,
       1.48067599e-04, 7.47183131e-05, 1.33642738e-05, 1.27803146e-04,
       2.11131500e-03, 7.58610286e-04, 8.68407216e-05, 3.99062500e-05,
       4.59786143e-04, 2.76330667e-04, 1.35475175e-04, 1.57885575e-04,
      

In [11]:
# training the model to predict generosity
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(generosity_train, generosity_train.values.ravel())
predictions = rf.predict(generosity_test)
errors = abs(predictions - generosity_test.values.ravel())
mape = 100 * (errors / generosity_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  97.40048972163262
Mean Absolute Error: 0.0 degrees


array([6.03830000e-04, 2.74586667e-04, 4.02708333e-05, 3.93424762e-05,
       1.96106825e-05, 2.38571429e-06, 3.25502305e-05, 8.92460000e-05,
       5.46309333e-04, 2.46826463e-04, 3.49610683e-04, 2.45369317e-04,
       1.65621752e-03, 1.67153571e-04, 1.13631825e-04, 5.83546429e-05,
       2.10389317e-04, 2.52350000e-04, 2.52204667e-04, 5.94200000e-05,
       2.39419264e-05, 2.24717028e-04, 2.80933537e-04, 5.11734524e-05,
       7.50669286e-05, 1.12262071e-04, 1.03291240e-04, 2.36402000e-04,
       5.82383333e-04, 1.78931476e-03, 3.95601667e-05, 2.63168333e-05,
       6.56783429e-04, 8.86703571e-05, 6.64123000e-04, 3.65844421e-04,
       4.47742595e-04, 2.19560000e-04, 1.58104000e-04, 6.71435714e-05,
       3.72474833e-04, 5.84463730e-05, 4.16510000e-04, 1.56055500e-04,
       8.08585714e-05, 1.19141429e-04, 1.31193333e-04, 1.90056307e-04,
       1.83290000e-04, 1.23242000e-03, 1.81634048e-04, 4.61298571e-05,
       6.55995214e-04, 1.74940000e-04, 8.91362302e-06, 2.90800000e-05,
      

In [12]:
# training the model to predict dystopia

rf = RandomForestRegressor(n_estimators=1000)
rf.fit(dystopia_train, dystopia_train.values.ravel())
predictions = rf.predict(dystopia_test)
errors = abs(predictions - dystopia_test.values.ravel())
mape = 100 * (errors / dystopia_test.values.ravel())
accuracy = 100 - np.mean(mape)
print('Accuracy: ',accuracy)
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')
errors

Accuracy:  99.87104082080315
Mean Absolute Error: 0.0 degrees


array([2.15320000e-04, 1.43732933e-03, 3.72937000e-03, 6.90190000e-04,
       2.90952633e-03, 1.03390800e-02, 6.94720000e-04, 1.24677024e-04,
       2.02076000e-03, 7.02303200e-03, 2.55290000e-04, 5.37783714e-04,
       4.56633333e-05, 1.09482250e-03, 1.11069750e-03, 8.30690000e-04,
       3.06565500e-03, 3.60630250e-04, 2.99824000e-03, 1.60589750e-04,
       4.02980476e-05, 3.78270000e-04, 4.53080000e-04, 1.92685350e-03,
       1.38843000e-03, 7.09400000e-05, 1.65229000e-03, 6.86530667e-04,
       7.70710000e-04, 8.80200000e-05, 6.36470000e-04, 6.06115000e-03,
       2.05790833e-03, 1.48282500e-03, 8.52520000e-04, 1.49683550e-03,
       7.30025000e-03, 1.45787200e-02, 1.37478690e-02, 2.45030400e-02,
       2.17373000e-03, 5.09775476e-04, 4.79180000e-04, 1.96334667e-04,
       4.36355600e-03, 5.70942000e-03, 5.64200000e-05, 6.69009333e-04,
       1.54183174e-05, 5.70000013e-07, 6.81250000e-04, 3.36440000e-04,
       2.86710000e-04, 1.64680000e-03, 1.32864333e-03, 8.51620000e-04,
      

In [13]:
lr=linear_model.LinearRegression()
lr.fit(df_train,y_train.values.ravel())

NameError: name 'y_train' is not defined

In [ ]:
predictions = lr.predict(df_test)
errors = abs(predictions - y_test.values.ravel())
errors

In [ ]:
print('Mean Absolute Error:',round(np.mean(errors),2),'degrees')

In [ ]:
mape = 100 * (errors / y_test.values.ravel())
accuracy = 100 - np.mean(mape)
print(accuracy)

In [ ]:
plt.scatter(y_test,predictions)