# Linear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import r2_score

In [2]:
df = pd.read_pickle('happiness_data.pkl')
df

Country  Year  Score   Economy    Family    Health  \
0             Afghanistan  2015  3.575  0.319820  0.302850  0.303350   
1             Afghanistan  2016  3.360  0.382270  0.110370  0.173440   
2             Afghanistan  2017  3.794  0.401477  0.581543  0.180747   
3                 Albania  2015  4.959  0.878670  0.804340  0.813250   
4                 Albania  2016  4.655  0.955300  0.501630  0.730070   
5                 Albania  2017  4.644  0.996193  0.803685  0.731160   
6                 Algeria  2015  5.605  0.939290  1.077720  0.617660   
7                 Algeria  2016  6.355  1.052660  0.833090  0.618040   
8                 Algeria  2017  5.872  1.091864  1.146217  0.617585   
9                  Angola  2015  4.033  0.757780  0.860400  0.166830   
10                 Angola  2016  3.866  0.847310  0.663660  0.049910   
11                 Angola  2017  3.795  0.858428  1.104412  0.049869   
12              Argentina  2015  6.574  1.053510  1.248230  0.787230   
13              Argentina  2016  6.650  1.151370  1.066120  0.697110   
14              Argentina  2017  6.599  1.185295  1.440451  0.695137   
15                Armenia  2015  4.350  0.768210  0.777110  0.729900   
16                Armenia  2016  4.360  0.860860  0.624770  0.640830   
17                Armenia  2017  4.376  0.900597  1.007484  0.637524   
18              Australia  2015  7.284  1.333580  1.309230  0.931560   
19              Australia  2016  7.313  1.444430  1.104760  0.851200   
20              Australia  2017  7.284  1.484415  1.510042  0.843887   
21                Austria  2015  7.200  1.337230  1.297040  0.890420   
22                Austria  2016  7.119  1.450380  1.083830  0.805650   
23                Austria  2017  7.006  1.487097  1.459945  0.815328   
24             Azerbaijan  2015  5.212  1.023890  0.937930  0.640450   
25             Azerbaijan  2016  5.291  1.123730  0.760420  0.545040   
26             Azerbaijan  2017  5.234  1.153602  1.152400  0.540776   
27                Bahrain  2015  5.960  1.323760  1.216240  0.747160   
28                Bahrain  2016  6.218  1.440240  0.943970  0.656960   
29                Bahrain  2017  6.087  1.488412  1.323110  0.653133   
..                    ...   ...    ...       ...       ...       ...   
363                Uganda  2015  3.931  0.211020  1.132990  0.338610   
364                Uganda  2016  3.739  0.347190  0.909810  0.196250   
365                Uganda  2017  4.081  0.381431  1.129828  0.217633   
366               Ukraine  2015  4.681  0.799070  1.202780  0.673900   
367               Ukraine  2016  4.324  0.872870  1.014130  0.586280   
368               Ukraine  2017  4.096  0.894652  1.394538  0.575904   
369  United Arab Emirates  2015  6.901  1.427270  1.125750  0.809250   
370  United Arab Emirates  2016  6.573  1.573520  0.871140  0.729930   
371  United Arab Emirates  2017  6.648  1.626343  1.266410  0.726798   
372        United Kingdom  2015  6.867  1.266370  1.285480  0.909430   
373        United Kingdom  2016  6.725  1.402830  1.086720  0.809910   
374        United Kingdom  2017  6.714  1.441634  1.496460  0.805336   
375         United States  2015  7.119  1.394510  1.247110  0.861790   
376         United States  2016  7.104  1.507960  1.047820  0.779000   
377         United States  2017  6.993  1.546259  1.419921  0.774287   
378               Uruguay  2015  6.485  1.061660  1.208900  0.811600   
379               Uruguay  2016  6.545  1.181570  1.031430  0.721830   
380               Uruguay  2017  6.454  1.217560  1.412228  0.719217   
381            Uzbekistan  2015  6.003  0.632440  1.340430  0.597720   
382            Uzbekistan  2016  5.987  0.735910  1.168100  0.501630   
383            Uzbekistan  2017  5.971  0.786441  1.548969  0.498273   
384               Vietnam  2015  5.360  0.632160  0.912260  0.746760   
385               Vietnam  2016  5.061  0.740370  0.791170  0.661570   
386               Vietnam  2017  5.074  0.788548  1.277491

In [3]:
years_train = [2015, 2016]
years_test = [2017]
train_features = df.loc[df['Year'].isin(years_train)]
test_features = df.loc[df['Year'].isin(years_test)]
train_features.reset_index(inplace=True, drop=True)
test_features.reset_index(inplace=True, drop=True)

In [4]:
df_train = train_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)
df_test = test_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)

In [5]:
#Fetching training and test data set
score_train = pd.DataFrame(train_features['Score'])
economy_train = pd.DataFrame(train_features['Economy'])
family_train = pd.DataFrame(train_features['Family'])
health_train = pd.DataFrame(train_features['Health'])
freedom_train = pd.DataFrame(train_features['Freedom'])
trust_train = pd.DataFrame(train_features['Trust'])
generosity_train = pd.DataFrame(train_features['Generosity'])
dystopia_train = pd.DataFrame(train_features['Dystopia'])

score_test = pd.DataFrame(test_features['Score'])
economy_test = pd.DataFrame(test_features['Economy'])
family_test = pd.DataFrame(test_features['Family'])
health_test = pd.DataFrame(test_features['Health'])
freedom_test = pd.DataFrame(test_features['Freedom'])
trust_test = pd.DataFrame(test_features['Trust'])
generosity_test = pd.DataFrame(test_features['Generosity'])
dystopia_test = pd.DataFrame(test_features['Dystopia'])

In [6]:
#Training the model to predict Economy
lr = linear_model.LinearRegression()
lr.fit(df_train, economy_train.values.ravel())
economy_predictions = lr.predict(df_test)
errors = abs(economy_predictions - economy_test.values.ravel())
accuracy = r2_score(economy_test.values.ravel(), economy_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.42686141336998196


array([0.35446612, 0.18511921, 0.40099947, 0.15706108, 0.1176685 ,
       0.0457608 , 0.08101253, 0.19364348, 0.0889114 , 0.55212388,
       0.12878589, 0.03135112, 0.61175697, 0.26081127, 0.01437686,
       0.14558076, 0.34325174, 0.17822183, 0.03202438, 0.61343087,
       0.10915312, 0.23951591, 0.30229318, 0.43281135, 0.96616203,
       0.52275321, 0.16265405, 0.0707414 , 0.07712718, 0.11681093,
       0.02158377, 0.23987319, 0.03278265, 0.26567953, 0.21474395,
       0.03207234, 0.1138853 , 0.51952503, 0.46970875, 0.15144466,
       0.33337679, 0.10291427, 0.14700571, 0.42221482, 0.37842665,
       0.31638677, 0.51652117, 0.25585398, 0.12646369, 0.24952462,
       0.02881833, 0.34657469, 0.2346461 , 0.09919592, 0.05917251,
       0.01902756, 0.01231985, 0.0852198 , 0.0260669 , 0.23692546,
       0.20084297, 0.40721837, 0.24545287, 0.10500676, 0.34839885,
       0.01837144, 0.38116131, 0.33378604, 0.3736095 , 0.12715183,
       0.56439816, 0.05179102, 0.34069416, 0.67968827, 0.41188

In [7]:
#Training the model to predict Family
lr = linear_model.LinearRegression()
lr.fit(df_train, family_train.values.ravel())
family_predictions = lr.predict(df_test)
errors = abs(family_predictions - family_test.values.ravel())
accuracy = r2_score(family_test.values.ravel(), family_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.9952424117521168


array([0.11607535, 0.02039443, 0.3716293 , 0.19770496, 0.41998156,
       0.19567236, 0.10314994, 0.3604574 , 0.19658043, 0.48434136,
       0.0801252 , 0.44220393, 0.67089751, 0.26877233, 0.42162435,
       0.30019739, 0.15113892, 0.35550859, 0.36226787, 0.64048999,
       0.45073297, 0.01024291, 0.45804583, 0.12150133, 0.53718995,
       0.07174282, 0.20870361, 0.44406063, 0.50935013, 0.47346339,
       0.01624462, 0.16917301, 0.30912707, 0.45320117, 0.55970065,
       0.3718094 , 0.25280815, 0.51277478, 0.03593456, 0.42670353,
       0.42296247, 0.27963007, 0.32789667, 0.51352855, 0.13661925,
       0.37199457, 0.50123915, 0.16904095, 0.10352154, 0.1153466 ,
       0.24935023, 0.50304853, 0.35744585, 0.3803108 , 0.23802956,
       0.42682696, 0.23040592, 0.41253369, 0.49360711, 0.35090428,
       0.35452195, 0.44751938, 0.3502746 , 0.33690712, 0.21304175,
       0.32646849, 0.49563866, 0.16741293, 0.59819369, 0.28159537,
       0.70409883, 0.39797958, 0.14202656, 0.53285482, 0.19086

In [8]:
#Training the model to predict Health
lr = linear_model.LinearRegression()
lr.fit(df_train, health_train.values.ravel())
health_predictions = lr.predict(df_test)
errors = abs(health_predictions - health_test.values.ravel())
accuracy = r2_score(health_test.values.ravel(), health_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.29497500754700323


array([0.33606703, 0.06442121, 0.31731459, 0.45942915, 0.05349163,
       0.07128551, 0.0331693 , 0.00920766, 0.16206325, 0.03549845,
       0.01954716, 0.11251238, 0.25261623, 0.24258886, 0.04101979,
       0.17913308, 0.13999588, 0.14726861, 0.0333773 , 0.24163518,
       0.04178433, 0.23850197, 0.08469366, 0.46322611, 0.42239539,
       0.41204622, 0.02449425, 0.02968709, 0.10137642, 0.04653361,
       0.13732507, 0.05377178, 0.10995175, 0.01719067, 0.05289492,
       0.02810003, 0.15241831, 0.06337832, 0.23439146, 0.07843217,
       0.15266391, 0.15338457, 0.05528645, 0.17777147, 0.29076072,
       0.1261765 , 0.10142751, 0.22099803, 0.14204316, 0.13984624,
       0.09025705, 0.06223565, 0.04331358, 0.01511024, 0.18646386,
       0.00743777, 0.04976925, 0.02354831, 0.03687057, 0.04306932,
       0.04100675, 0.11651505, 0.22576089, 0.10759653, 0.0189914 ,
       0.17661086, 0.28233578, 0.31193977, 0.17312035, 0.16181003,
       0.23863807, 0.04655773, 0.23481359, 0.25224573, 0.42660

In [9]:
#Training the model to predict Freedom
lr = linear_model.LinearRegression()
lr.fit(df_train, freedom_train.values.ravel())
freedom_predictions = lr.predict(df_test)
errors = abs(freedom_predictions - freedom_test.values.ravel())
accuracy = r2_score(freedom_test.values.ravel(), freedom_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.15374436207866649


array([0.17830903, 0.07783297, 0.07639618, 0.46164952, 0.08258623,
       0.12811001, 0.00746328, 0.07730705, 0.10253519, 0.08724669,
       0.06542657, 0.07034044, 0.232262  , 0.19713729, 0.10522123,
       0.08414248, 0.082994  , 0.14201665, 0.062832  , 0.09519908,
       0.03490635, 0.3390543 , 0.41899138, 0.08300754, 0.3539027 ,
       0.38317677, 0.10431829, 0.01802638, 0.00225574, 0.20152177,
       0.18934595, 0.106453  , 0.10708655, 0.09362693, 0.10639206,
       0.03678705, 0.02673475, 0.08943176, 0.12439482, 0.09640862,
       0.06311803, 0.00579433, 0.04120178, 0.1851123 , 0.16061255,
       0.07412977, 0.27598843, 0.13473061, 0.40169794, 0.04908799,
       0.27360162, 0.10643676, 0.15644363, 0.20986323, 0.13250451,
       0.0933993 , 0.06753164, 0.11579582, 0.15408295, 0.02374945,
       0.05591818, 0.09904765, 0.16463727, 0.04247232, 0.2461599 ,
       0.02725728, 0.06688778, 0.03272577, 0.08503171, 0.23259506,
       0.23211679, 0.16230403, 0.1033116 , 0.17542917, 0.27440

In [10]:
#Training the model to predict Trust
lr = linear_model.LinearRegression()
lr.fit(df_train, trust_train.values.ravel())
trust_predictions = lr.predict(df_test)
errors = abs(trust_predictions - trust_test.values.ravel())
accuracy = r2_score(trust_test.values.ravel(), trust_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.3404935027172562


array([9.95609514e-02, 2.72008450e-02, 1.72437981e-01, 1.93276729e-01,
       9.09061634e-02, 1.15126713e-01, 1.18215036e-02, 3.27105334e-02,
       2.88414213e-02, 1.35729181e-01, 1.64899833e-02, 4.27623932e-02,
       1.92544366e-01, 2.05158682e-01, 6.17036526e-02, 8.56022705e-02,
       1.54752688e-02, 1.40749769e-01, 3.26829758e-02, 4.55394245e-02,
       3.20947138e-02, 7.73059322e-02, 8.47916487e-02, 2.25092053e-01,
       2.67645624e-01, 2.72281272e-01, 8.73685714e-02, 5.85626318e-02,
       8.38938025e-02, 3.92574267e-03, 1.32065262e-01, 1.34606084e-01,
       2.45601295e-01, 1.56167920e-01, 8.49399973e-02, 5.15582930e-02,
       5.04974787e-03, 1.10212460e-01, 7.95482250e-02, 1.74905102e-01,
       8.49262343e-02, 1.42314753e-01, 7.41087083e-02, 1.90511316e-01,
       1.35634726e-01, 5.74391038e-02, 1.13941237e-01, 1.37955928e-01,
       2.57654369e-02, 4.60223103e-02, 8.78088178e-02, 5.37560569e-03,
       1.19478602e-01, 6.03329884e-02, 3.68979346e-02, 7.15569479e-02,
      

In [11]:
#Training the model to predict Generosity
lr = linear_model.LinearRegression()
lr.fit(df_train, generosity_train.values.ravel())
generosity_predictions = lr.predict(df_test)
errors = abs(generosity_predictions - generosity_test.values.ravel())
accuracy = r2_score(generosity_test.values.ravel(), generosity_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.22553886701585113


array([0.09587494, 0.05548728, 0.02052035, 0.18147371, 0.10268586,
       0.1277137 , 0.08990627, 0.1358746 , 0.14594745, 0.00247219,
       0.11177739, 0.02418671, 0.17360468, 0.20989497, 0.25099856,
       0.10481302, 0.25069529, 0.22167778, 0.0907231 , 0.00491952,
       0.00921544, 0.0969126 , 0.20924742, 0.11855765, 0.24344679,
       0.14260468, 0.11184203, 0.03098271, 0.06097582, 0.0664436 ,
       0.10587492, 0.13531502, 0.1553431 , 0.17616087, 0.04529513,
       0.00052139, 0.1002119 , 0.01152879, 0.0732647 , 0.05866701,
       0.05564696, 0.12947652, 0.12613382, 0.24940072, 0.01995167,
       0.13714651, 0.08427081, 0.15583949, 0.10146112, 0.06685588,
       0.27082192, 0.07566046, 0.02378597, 0.47796404, 0.0078242 ,
       0.13949235, 0.04645753, 0.07716896, 0.04382757, 0.10834596,
       0.02838493, 0.04508616, 0.18292709, 0.11105816, 0.07953559,
       0.10440382, 0.10067587, 0.02049667, 0.22611346, 0.24550954,
       0.06687439, 0.10656731, 0.25398439, 0.35755572, 0.33314

In [12]:
#Training the model to predict Dystopia
lr = linear_model.LinearRegression()
lr.fit(df_train, dystopia_train.values.ravel())
dystopia_predictions = lr.predict(df_test)
errors = abs(dystopia_predictions - dystopia_test.values.ravel())
accuracy = r2_score(dystopia_test.values.ravel(), dystopia_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -1.051872005906521


array([0.68191676, 0.67086292, 1.15672064, 1.26814219, 0.11187998,
       0.41646486, 0.82601143, 0.04445609, 0.28207397, 0.0631666 ,
       0.29009595, 0.45345354, 0.72420188, 1.2281532 , 0.75354963,
       0.36468278, 0.00447483, 1.72540334, 0.01283488, 0.14252656,
       0.02306119, 0.60779813, 0.04134139, 0.4797835 , 0.75118745,
       1.35558625, 0.1646863 , 0.45649492, 0.10727964, 0.64309442,
       0.54339201, 0.77423306, 0.05053236, 0.06707675, 1.19131007,
       0.37889952, 0.08744997, 0.23067467, 0.71969048, 0.22951777,
       0.03248686, 0.63105929, 0.32580553, 0.33961712, 0.58141796,
       0.09159159, 1.03837438, 0.56504698, 0.86519794, 0.20537655,
       0.40616469, 0.14577043, 0.75380968, 0.54796915, 1.8057052 ,
       0.00781149, 0.35725108, 0.39624971, 0.64214424, 0.95847574,
       0.60512808, 0.02308509, 0.59564796, 0.69062305, 0.29691122,
       0.08241179, 0.29060502, 1.41449747, 0.23324958, 0.18580813,
       0.62338371, 0.0742357 , 0.88894891, 1.19100763, 1.40236

In [13]:
#Predicting Score
predictions = economy_predictions + family_predictions + health_predictions + freedom_predictions + trust_predictions + generosity_predictions + dystopia_predictions
errors = abs(predictions - score_test.values.ravel())
accuracy = r2_score(score_test.values.ravel(), predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.5503499721225034


array([1.62989635, 0.28135087, 2.51587976, 2.52316538, 0.48542743,
       0.70835913, 0.5807987 , 0.8350656 , 0.61346422, 1.36031553,
       0.38828662, 0.15880631, 2.85787056, 2.61230323, 0.03102245,
       0.49552836, 0.79071264, 1.55979874, 0.37816688, 1.49903128,
       0.70082265, 1.58838096, 1.59927206, 1.68083183, 3.54154227,
       3.01698485, 0.48097252, 0.22018085, 0.23062383, 1.55168358,
       0.89111258, 0.4170284 , 0.32640442, 1.06073406, 0.49323582,
       0.15550988, 0.00538494, 1.05262036, 1.66506953, 0.59997585,
       1.08059968, 0.88579958, 0.94921934, 2.07847959, 1.10864144,
       0.56878575, 2.63202216, 1.30095996, 1.5632233 , 0.64087968,
       0.85075553, 1.23464725, 0.09478598, 0.69465697, 2.27427664,
       0.73510785, 0.44324917, 0.16861687, 0.12447783, 0.37602088,
       0.05551038, 1.1771127 , 0.45242349, 0.54327496, 0.83066205,
       0.09258237, 1.57472842, 2.07400968, 0.36775908, 0.54338742,
       2.53888923, 0.22000692, 2.14107729, 3.30314511, 2.89932