# Linear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import r2_score

In [2]:
df = pd.read_pickle('happiness_data.pkl')

In [3]:
years_train = [2015, 2016]
years_test = [2017]
train_features = df.loc[df['Year'].isin(years_train)]
test_features = df.loc[df['Year'].isin(years_test)]
train_features.reset_index(inplace=True, drop=True)
test_features.reset_index(inplace=True, drop=True)

In [4]:
df_train = train_features.drop(columns=['Country', 'Year', 'Score', 'Low', 'High', 'Economy', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia'], axis=1)
df_test = test_features.drop(columns=['Country', 'Year', 'Score', 'Low', 'High', 'Economy', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia'], axis=1)

In [5]:
df_economy_train = pd.read_pickle('economy_train.pkl')
df_family_train = pd.read_pickle('family_train.pkl')
df_health_train = pd.read_pickle('health_train.pkl')
df_trust_train = pd.read_pickle('trust_train.pkl')
df_generosity_train = pd.read_pickle('generosity_train.pkl')
df_freedom_train = pd.read_pickle('freedom_train.pkl')
df_dystopia_train = pd.read_pickle('dystopia_train.pkl')




In [6]:
df_economy_test = pd.read_pickle('economy_test.pkl')
df_family_test = pd.read_pickle('family_test.pkl')
df_health_test = pd.read_pickle('health_test.pkl')
df_trust_test = pd.read_pickle('trust_test.pkl')
df_generosity_test = pd.read_pickle('generosity_test.pkl')
df_freedom_test = pd.read_pickle('freedom_test.pkl')
df_dystopia_test = pd.read_pickle('dystopia_test.pkl')

In [7]:
#Fetching training and test data set
score_train = pd.DataFrame(train_features['Score'])
economy_train = pd.DataFrame(train_features['Economy'])
family_train = pd.DataFrame(train_features['Family'])
health_train = pd.DataFrame(train_features['Health'])
freedom_train = pd.DataFrame(train_features['Freedom'])
trust_train = pd.DataFrame(train_features['Trust'])
generosity_train = pd.DataFrame(train_features['Generosity'])
dystopia_train = pd.DataFrame(train_features['Dystopia'])

score_test = pd.DataFrame(test_features['Score'])
economy_test = pd.DataFrame(test_features['Economy'])
family_test = pd.DataFrame(test_features['Family'])
health_test = pd.DataFrame(test_features['Health'])
freedom_test = pd.DataFrame(test_features['Freedom'])
trust_test = pd.DataFrame(test_features['Trust'])
generosity_test = pd.DataFrame(test_features['Generosity'])
dystopia_test = pd.DataFrame(test_features['Dystopia'])

low_score = pd.DataFrame(test_features['Low'])
high_score = pd.DataFrame(test_features['High'])

In [8]:
#Training the model to predict Economy
lr = linear_model.LinearRegression()
lr.fit(df_economy_train, economy_train.values.ravel())
economy_predictions = lr.predict(df_economy_test)
errors = abs(economy_predictions - economy_test.values.ravel())
accuracy = r2_score(economy_test.values.ravel(), economy_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.5203426548212446


array([3.45801016e-01, 1.32566273e-01, 3.37838968e-01, 7.78034253e-02,
       1.15915696e-01, 2.87496561e-02, 1.89110594e-01, 1.90421337e-01,
       8.37116925e-02, 5.38413387e-01, 1.71527315e-01, 1.14648108e-01,
       5.11806212e-01, 1.07092280e-01, 3.35112901e-02, 1.17395778e-01,
       2.93133964e-01, 1.43323410e-01, 7.70823076e-02, 4.98448240e-01,
       1.28568410e-01, 2.82271434e-01, 2.20836958e-01, 3.54035347e-01,
       8.99533178e-01, 3.42209251e-01, 1.34416648e-01, 1.39158098e-01,
       7.28629503e-02, 6.37169594e-02, 6.37306916e-02, 2.00220480e-01,
       1.52238476e-02, 2.24023788e-01, 1.61754088e-01, 1.15159335e-01,
       7.14526220e-02, 4.43664899e-01, 4.73444461e-01, 1.07580866e-01,
       3.17181096e-01, 1.08232383e-01, 1.82150791e-01, 4.15683196e-01,
       3.62905943e-01, 2.83541829e-01, 4.45443741e-01, 1.08946529e-01,
       6.78307704e-04, 2.02129692e-01, 1.14925324e-01, 4.46439719e-01,
       5.74203066e-02, 9.50952480e-02, 1.46620554e-02, 7.76899742e-02,
      

In [9]:
#Training the model to predict Family
lr = linear_model.LinearRegression()
lr.fit(df_family_train, family_train.values.ravel())
family_predictions = lr.predict(df_family_test)
errors = abs(family_predictions - family_test.values.ravel())
accuracy = r2_score(family_test.values.ravel(), family_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.7273283475856691


array([0.134872  , 0.06412446, 0.24364251, 0.34446228, 0.39893843,
       0.07795045, 0.08748642, 0.33884511, 0.21884136, 0.39909601,
       0.08609913, 0.44760564, 0.55232231, 0.1307521 , 0.45469838,
       0.34970323, 0.21482664, 0.4442111 , 0.35815264, 0.5027386 ,
       0.37725458, 0.05914896, 0.2755258 , 0.22138025, 0.35584764,
       0.2778548 , 0.24238718, 0.360541  , 0.55956813, 0.50180942,
       0.00480456, 0.15346622, 0.31531466, 0.44343184, 0.54620631,
       0.35717733, 0.29618003, 0.4182433 , 0.11027347, 0.49071565,
       0.3592606 , 0.20484329, 0.43448472, 0.46252537, 0.10810143,
       0.29934074, 0.45500097, 0.11892712, 0.02715143, 0.14438381,
       0.24157972, 0.49341497, 0.40540172, 0.34467658, 0.08546186,
       0.38346128, 0.22874405, 0.40656711, 0.52483482, 0.38197577,
       0.38208932, 0.35774161, 0.3888884 , 0.32366541, 0.1983875 ,
       0.24601344, 0.25058428, 0.19814456, 0.30141477, 0.3981937 ,
       0.52135716, 0.3248414 , 0.04938546, 0.33381931, 0.42614

In [10]:
#Training the model to predict Health
lr = linear_model.LinearRegression()
lr.fit(df_health_train, health_train.values.ravel())
health_predictions = lr.predict(df_health_test)
errors = abs(health_predictions - health_test.values.ravel())
accuracy = r2_score(health_test.values.ravel(), health_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.8284132721674273


array([1.25051469e-01, 3.38151930e-02, 1.93676870e-02, 1.68463673e-01,
       1.90226829e-04, 5.29909685e-02, 3.90515617e-02, 3.09794590e-03,
       1.08036287e-01, 7.47905801e-02, 2.18174393e-02, 1.25427817e-01,
       3.80193149e-02, 6.82168808e-02, 1.04140634e-01, 9.13609500e-02,
       7.15400531e-04, 1.58079173e-01, 4.15901275e-02, 1.67618909e-02,
       1.66250272e-02, 1.76801063e-01, 1.86454601e-01, 1.36199879e-01,
       4.79550941e-02, 8.76497640e-03, 4.16847178e-02, 8.33404447e-02,
       6.06717734e-02, 3.17319615e-02, 7.89513875e-02, 4.45028668e-02,
       8.31774468e-02, 2.50935508e-02, 6.98677913e-02, 3.08181692e-02,
       1.29641988e-01, 1.53215563e-01, 9.09796049e-02, 8.52516253e-03,
       3.15761968e-02, 1.24426694e-01, 6.88985505e-02, 1.79667543e-03,
       1.75926842e-01, 5.56672595e-02, 7.10136115e-02, 2.03558236e-02,
       4.63824750e-02, 1.24442395e-01, 1.13237958e-01, 3.14018429e-02,
       1.15602973e-02, 1.04396104e-01, 1.08310649e-01, 1.26607394e-02,
      

In [11]:
#Training the model to predict Freedom
lr = linear_model.LinearRegression()
lr.fit(df_freedom_train, freedom_train.values.ravel())
freedom_predictions = lr.predict(df_freedom_test)
errors = abs(freedom_predictions - freedom_test.values.ravel())
accuracy = r2_score(freedom_test.values.ravel(), freedom_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.3458093443440541


array([0.07426553, 0.03519847, 0.09010614, 0.25453201, 0.07054736,
       0.15582835, 0.03631973, 0.08796918, 0.02939464, 0.05832425,
       0.04213472, 0.13068959, 0.08481283, 0.05434773, 0.03736899,
       0.14337541, 0.11524657, 0.19455309, 0.01227637, 0.1848941 ,
       0.02217075, 0.26682086, 0.2155398 , 0.11220023, 0.07289414,
       0.07720635, 0.10813453, 0.05172135, 0.04721778, 0.20073476,
       0.17563447, 0.09733444, 0.09516126, 0.08130155, 0.1136077 ,
       0.03864611, 0.05728126, 0.05299039, 0.02547561, 0.16130764,
       0.02040984, 0.03781883, 0.11500191, 0.05392346, 0.16655675,
       0.14766917, 0.15775952, 0.10047959, 0.30821692, 0.07625748,
       0.30380038, 0.08136539, 0.19852669, 0.09119611, 0.00065115,
       0.06653114, 0.0227689 , 0.11407711, 0.14184986, 0.07031838,
       0.09142297, 0.02623732, 0.31501109, 0.04945878, 0.13278693,
       0.06408149, 0.06978919, 0.0793825 , 0.0232687 , 0.18977816,
       0.08615033, 0.20610293, 0.04572763, 0.07873857, 0.02397

In [12]:
#Training the model to predict Trust
lr = linear_model.LinearRegression()
lr.fit(df_trust_train, trust_train.values.ravel())
trust_predictions = lr.predict(df_trust_test)
errors = abs(trust_predictions - trust_test.values.ravel())
accuracy = r2_score(trust_test.values.ravel(), trust_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.22498972270750883


array([0.06662444, 0.01895668, 0.02543145, 0.04914506, 0.11694761,
       0.11189566, 0.05103758, 0.01811523, 0.01664738, 0.05797552,
       0.00586264, 0.00786919, 0.07122126, 0.01780341, 0.02357876,
       0.03421682, 0.09227995, 0.06132467, 0.00091972, 0.13673494,
       0.01725985, 0.03392785, 0.10955889, 0.02966586, 0.0142263 ,
       0.02213107, 0.07223868, 0.08567068, 0.07700148, 0.00800463,
       0.07288687, 0.14818995, 0.22402796, 0.18093889, 0.06669068,
       0.03556249, 0.02944847, 0.04911493, 0.0282993 , 0.21895907,
       0.01478828, 0.07695322, 0.09341956, 0.06635905, 0.04286924,
       0.00273504, 0.01230967, 0.01733295, 0.05458848, 0.06403728,
       0.12607574, 0.0063715 , 0.14280961, 0.04480913, 0.07500926,
       0.0801798 , 0.04920606, 0.05737037, 0.00367934, 0.01694388,
       0.01705537, 0.08476741, 0.00125263, 0.12432108, 0.07346597,
       0.0847461 , 0.12243843, 0.02752647, 0.08189825, 0.13625565,
       0.01242906, 0.10601297, 0.08353083, 0.11772443, 0.01233

In [13]:
#Training the model to predict Generosity
lr = linear_model.LinearRegression()
lr.fit(df_generosity_train, generosity_train.values.ravel())
generosity_predictions = lr.predict(df_generosity_test)
errors = abs(generosity_predictions - generosity_test.values.ravel())
accuracy = r2_score(generosity_test.values.ravel(), generosity_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.16864179575453264


array([1.08816793e-01, 6.73333904e-02, 1.53804553e-01, 7.82070394e-02,
       8.74362772e-02, 9.15669523e-02, 1.74769151e-01, 9.03662250e-02,
       1.41941038e-01, 5.19767555e-02, 2.70251346e-02, 2.66193634e-04,
       1.96345436e-02, 2.06344066e-02, 2.48831305e-01, 4.37620378e-03,
       1.51607978e-01, 1.06694328e-01, 4.47786012e-02, 1.44108815e-01,
       1.72199774e-02, 6.35159597e-02, 1.23794813e-01, 2.61342848e-02,
       1.11870100e-01, 3.47867221e-02, 8.68986421e-02, 1.08384594e-01,
       2.50124743e-02, 8.54129384e-02, 1.15535842e-01, 1.13135317e-01,
       1.52326177e-01, 1.12302866e-01, 2.90806250e-02, 5.46526117e-02,
       1.00608218e-01, 1.17699163e-01, 1.34946207e-01, 8.39837625e-02,
       4.50372713e-02, 6.56802647e-02, 8.84651149e-02, 1.06972833e-01,
       1.13260649e-01, 1.62747036e-01, 1.43759471e-02, 8.37616426e-03,
       2.27104768e-01, 2.82481143e-02, 2.24422260e-01, 4.70643602e-02,
       6.88383123e-02, 3.43888517e-01, 1.48683126e-01, 8.93436219e-02,
      

In [14]:
#Training the model to predict Dystopia
lr = linear_model.LinearRegression()
lr.fit(df_dystopia_train, dystopia_train.values.ravel())
dystopia_predictions = lr.predict(df_dystopia_test)
errors = abs(dystopia_predictions - dystopia_test.values.ravel())
accuracy = r2_score(dystopia_test.values.ravel(), dystopia_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.32692121974004285


array([0.45666528, 0.72030567, 0.58624198, 0.65406996, 0.22433459,
       0.41980191, 0.1778795 , 0.09559322, 0.36355212, 0.29494539,
       0.40623368, 0.45127719, 0.11926531, 0.37373584, 0.95322024,
       0.11974442, 0.04716016, 1.50366376, 0.42857235, 0.98827304,
       0.0494528 , 0.47986109, 0.79901366, 0.1409214 , 0.31791726,
       0.24927623, 0.21481922, 0.19481624, 0.09560183, 0.75182599,
       0.27003252, 0.59741594, 0.11443787, 0.04718654, 1.09933193,
       0.14896881, 0.01016633, 0.68118778, 0.08206637, 0.05572541,
       0.39648063, 0.67624035, 0.4526367 , 0.30955373, 0.39023873,
       0.33981784, 0.62949207, 0.18693743, 0.65705529, 0.33353207,
       0.66384549, 0.13292267, 0.72884526, 0.8823659 , 1.56530557,
       0.15673959, 0.38317215, 0.42384008, 0.67207874, 1.15006768,
       0.66134414, 0.13762439, 0.202749  , 0.37425553, 0.75728729,
       0.17254921, 0.27104016, 0.86178089, 0.19600206, 0.01790873,
       0.00684067, 0.16426484, 0.76212658, 0.15755959, 0.41750

In [15]:
#Predicting Score
predictions = economy_predictions + family_predictions + health_predictions + freedom_predictions + trust_predictions + generosity_predictions + dystopia_predictions
errors = abs(predictions - score_test.values.ravel())
accuracy = r2_score(score_test.values.ravel(), predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.5887203946739774


array([6.91246947e-01, 7.36925694e-01, 9.17610240e-01, 9.37596847e-01,
       6.05556769e-01, 7.82452934e-01, 3.99850603e-01, 6.33045906e-01,
       4.90818999e-01, 6.31833612e-01, 4.48994167e-01, 3.82341919e-01,
       1.35779962e+00, 5.27240046e-01, 3.25973782e-01, 1.25928152e-01,
       4.03791748e-01, 1.04812065e+00, 7.88420393e-01, 4.69242173e-01,
       4.85178836e-01, 1.24358432e+00, 2.59462237e-01, 1.91198700e-02,
       1.79140344e+00, 3.69695665e-01, 5.40112334e-01, 3.02296766e-01,
       6.12492897e-01, 1.62711753e+00, 5.50703000e-01, 3.31484694e-01,
       1.09515557e-01, 9.69883908e-01, 4.43035306e-01, 6.70536352e-02,
       6.06053291e-02, 1.92798147e-01, 3.47501509e-01, 1.12659442e+00,
       2.72513705e-01, 8.84994350e-01, 1.24821632e+00, 7.98030158e-01,
       5.83703454e-01, 9.29248250e-03, 1.61900845e+00, 3.06324941e-01,
       7.03483032e-01, 6.83775901e-01, 1.07514678e+00, 9.60688450e-01,
       1.32700178e-01, 1.56865763e-01, 1.64763706e+00, 5.27859488e-01,
      

In [16]:
#Find accuracy
rows = len(predictions)
tp = 0
for i in range(rows):
    if(predictions[i] >= low_score.loc[i, 'Low'] and predictions[i] <= high_score.loc[i, 'High']):
        tp = tp + 1
print('Accuracy: ', tp/rows*100)

Accuracy:  9.16030534351145
