# Random Forest Regressor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [2]:
df = pd.read_pickle('happiness_data.pkl')
df

Country  Year  Score       Low      High   Economy  \
0             Afghanistan  2015  3.575  3.544160  3.605840  0.319820   
1             Afghanistan  2016  3.360  3.288000  3.432000  0.382270   
2             Afghanistan  2017  3.794  3.714338  3.873661  0.401477   
3                 Albania  2015  4.959  4.908870  5.009130  0.878670   
4                 Albania  2016  4.655  4.546000  4.764000  0.955300   
5                 Albania  2017  4.644  4.535536  4.752464  0.996193   
6                 Algeria  2015  5.605  5.554010  5.655990  0.939290   
7                 Algeria  2016  6.355  6.227000  6.483000  1.052660   
8                 Algeria  2017  5.872  5.765714  5.978286  1.091864   
9                  Angola  2015  4.033  3.985420  4.080580  0.757780   
10                 Angola  2016  3.866  3.753000  3.979000  0.847310   
11                 Angola  2017  3.795  3.638358  3.951642  0.858428   
12              Argentina  2015  6.574  6.527880  6.620120  1.053510   
13              Argentina  2016  6.650  6.560000  6.740000  1.151370   
14              Argentina  2017  6.599  6.507915  6.690085  1.185295   
15                Armenia  2015  4.350  4.302370  4.397630  0.768210   
16                Armenia  2016  4.360  4.266000  4.454000  0.860860   
17                Armenia  2017  4.376  4.285265  4.466735  0.900597   
18              Australia  2015  7.284  7.243170  7.324830  1.333580   
19              Australia  2016  7.313  7.241000  7.385000  1.444430   
20              Australia  2017  7.284  7.211349  7.356651  1.484415   
21                Austria  2015  7.200  7.162490  7.237510  1.337230   
22                Austria  2016  7.119  7.045000  7.193000  1.450380   
23                Austria  2017  7.006  6.941330  7.070670  1.487097   
24             Azerbaijan  2015  5.212  5.178370  5.245630  1.023890   
25             Azerbaijan  2016  5.291  5.226000  5.356000  1.123730   
26             Azerbaijan  2017  5.234  5.168714  5.299287  1.153602   
27                Bahrain  2015  5.960  5.905880  6.014120  1.323760   
28                Bahrain  2016  6.218  6.128000  6.308000  1.440240   
29                Bahrain  2017  6.087  5.995011  6.178989  1.488412   
..                    ...   ...    ...       ...       ...       ...   
363                Uganda  2015  3.931  3.887830  3.974170  0.211020   
364                Uganda  2016  3.739  3.629000  3.849000  0.347190   
365                Uganda  2017  4.081  3.966200  4.195800  0.381431   
366               Ukraine  2015  4.681  4.636880  4.725120  0.799070   
367               Ukraine  2016  4.324  4.236000  4.412000  0.872870   
368               Ukraine  2017  4.096  4.006590  4.185410  0.894652   
369  United Arab Emirates  2015  6.901  6.863710  6.938290  1.427270   
370  United Arab Emirates  2016  6.573  6.494000  6.652000  1.573520   
371  United Arab Emirates  2017  6.648  6.573952  6.722047  1.626343   
372        United Kingdom  2015  6.867  6.848340  6.885660  1.266370   
373        United Kingdom  2016  6.725  6.647000  6.803000  1.402830   
374        United Kingdom  2017  6.714  6.644209  6.783792  1.441634   
375         United States  2015  7.119  7.080610  7.157390  1.394510   
376         United States  2016  7.104  7.020000  7.188000  1.507960   
377         United States  2017  6.993  6.911343  7.074657  1.546259   
378               Uruguay  2015  6.485  6.439610  6.530390  1.061660   
379               Uruguay  2016  6.545  6.456000  6.634000  1.181570   
380               Uruguay  2017  6.454  6.362094  6.545906  1.217560   
381            Uzbekistan  2015  6.003  5.959390  6.046610  0.632440   
382            Uzbekistan  2016  5.987  5.896000  6.078000  0.735910   
383            Uzbekistan  2017  5.971  5.876463  6.065538  0.786441   
384               Vietnam  2015  5.360  5.328930  5.391070  0.632160   
385               Vietnam  2016  5.061  4.991000  5.131000  0.740370   
386               Vietnam  2017  5.074  5.000719  5.147281

In [3]:
years_train = [2015, 2016]
years_test = [2017]
train_features = df.loc[df['Year'].isin(years_train)]
test_features = df.loc[df['Year'].isin(years_test)]
train_features.reset_index(inplace=True, drop=True)
test_features.reset_index(inplace=True, drop=True)

In [4]:
df_train = train_features.drop(columns=['Country', 'Year', 'Score', 'Low', 'High', 'Economy', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia'], axis=1)
df_test = test_features.drop(columns=['Country', 'Year', 'Score', 'Low', 'High', 'Economy', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia'], axis=1)

In [5]:
#Fetching training and test data set
score_train = pd.DataFrame(train_features['Score'])
economy_train = pd.DataFrame(train_features['Economy'])
family_train = pd.DataFrame(train_features['Family'])
health_train = pd.DataFrame(train_features['Health'])
freedom_train = pd.DataFrame(train_features['Freedom'])
trust_train = pd.DataFrame(train_features['Trust'])
generosity_train = pd.DataFrame(train_features['Generosity'])
dystopia_train = pd.DataFrame(train_features['Dystopia'])

score_test = pd.DataFrame(test_features['Score'])
economy_test = pd.DataFrame(test_features['Economy'])
family_test = pd.DataFrame(test_features['Family'])
health_test = pd.DataFrame(test_features['Health'])
freedom_test = pd.DataFrame(test_features['Freedom'])
trust_test = pd.DataFrame(test_features['Trust'])
generosity_test = pd.DataFrame(test_features['Generosity'])
dystopia_test = pd.DataFrame(test_features['Dystopia'])

low_score = pd.DataFrame(test_features['Low'])
high_score = pd.DataFrame(test_features['High'])

In [6]:
#Training the model to predict Economy
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, economy_train.values.ravel())
economy_predictions = rf.predict(df_test)
errors = abs(economy_predictions - economy_test.values.ravel())
accuracy = r2_score(economy_test.values.ravel(), economy_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.6395964218667913


array([4.46568528e-01, 4.85615852e-04, 2.37132114e-01, 7.25968952e-02,
       1.39460554e-01, 2.22501007e-02, 7.22946243e-02, 1.45993449e-01,
       1.42292664e-01, 5.43131596e-01, 1.07968689e-01, 1.30682975e-02,
       6.42706922e-01, 4.65892872e-02, 8.55418410e-02, 2.24667664e-02,
       1.81526593e-02, 1.91714179e-01, 1.23951490e-01, 4.55920718e-01,
       1.18047903e-01, 1.14159831e-01, 8.30963910e-02, 1.02137847e-01,
       7.51625114e-01, 1.26254920e-01, 8.80661108e-02, 1.38501184e-01,
       9.11650869e-02, 8.50476219e-02, 1.67637621e-02, 5.52316185e-02,
       3.42150512e-02, 1.39039173e-01, 1.56128700e-01, 6.14481863e-02,
       1.29700854e-03, 5.22982406e-01, 3.66360374e-01, 1.17438878e-01,
       9.23914036e-02, 1.89740436e-01, 7.08845892e-02, 5.61882897e-01,
       6.15656321e-02, 5.69689578e-02, 3.81961031e-01, 4.68711509e-02,
       6.65864288e-02, 7.32709347e-02, 2.51376031e-02, 1.49388854e-01,
       1.36418103e-02, 8.29540477e-02, 1.12282055e-01, 1.01957839e-01,
      

In [7]:
#Training the model to predict Family
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, family_train.values.ravel())
family_predictions = rf.predict(df_test)
errors = abs(family_predictions - family_test.values.ravel())
accuracy = r2_score(family_test.values.ravel(), family_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  -0.6803104368680684


array([0.22490878, 0.04304675, 0.22424393, 0.38535062, 0.36560285,
       0.28016089, 0.37270607, 0.37427004, 0.21167441, 0.35732008,
       0.06061129, 0.30717847, 0.38399771, 0.10288467, 0.37970204,
       0.31501962, 0.29127337, 0.36061592, 0.40482786, 0.42448327,
       0.43041689, 0.08373004, 0.24588251, 0.3334329 , 0.42333701,
       0.26059445, 0.24581162, 0.23581392, 0.33098455, 0.4597972 ,
       0.0962152 , 0.07969962, 0.3142768 , 0.38685829, 0.44644666,
       0.3077425 , 0.25505515, 0.42796669, 0.23887139, 0.33075475,
       0.31021465, 0.35167532, 0.14205478, 0.3647854 , 0.29380996,
       0.37593969, 0.3725232 , 0.27381315, 0.09806367, 0.24116267,
       0.09677532, 0.4932099 , 0.14004803, 0.32289742, 0.10110296,
       0.43263193, 0.27753515, 0.32610132, 0.39329416, 0.37249122,
       0.27671518, 0.4381532 , 0.24548461, 0.40648041, 0.25357334,
       0.37375514, 0.29279478, 0.22670971, 0.42797816, 0.31446412,
       0.40436835, 0.29965885, 0.07029693, 0.32769501, 0.49870

In [8]:
#Training the model to predict Health
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, health_train.values.ravel())
health_predictions = rf.predict(df_test)
errors = abs(health_predictions - family_test.values.ravel())
accuracy = r2_score(health_test.values.ravel(), health_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.8750526995293265


array([0.31039626, 0.05636806, 0.54815854, 0.85442165, 0.70237246,
       0.30457327, 0.67084414, 0.64646484, 0.55003277, 0.63076773,
       0.19494164, 0.66566365, 0.63476761, 0.12056939, 0.78414702,
       0.68929715, 0.32658522, 0.72065472, 0.77461726, 0.72909354,
       0.78002916, 0.37442454, 0.4777387 , 0.72785203, 0.66835356,
       0.83728003, 0.47006031, 0.42238871, 0.71394156, 0.63910349,
       0.18453852, 0.28987227, 0.61409116, 0.75188998, 0.80556476,
       0.61338313, 0.50271983, 0.68986623, 0.47978957, 0.67374396,
       0.52984177, 0.8947217 , 0.10936806, 0.67397695, 0.57053426,
       0.44347349, 0.68942594, 0.53409492, 0.29778667, 0.49618093,
       0.48978446, 0.75204724, 0.30501423, 0.71065156, 0.39595008,
       0.70746278, 0.50295952, 0.57846845, 0.72829469, 0.51027268,
       0.61042794, 0.71631427, 0.76699293, 0.4699891 , 0.53525525,
       0.62971209, 0.39969481, 0.54456875, 0.71312115, 0.65825481,
       0.61672803, 0.56766437, 0.19086693, 0.59842915, 1.05381

In [9]:
#Training the model to predict Freedom
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, freedom_train.values.ravel())
freedom_predictions = rf.predict(df_test)
errors = abs(freedom_predictions - freedom_test.values.ravel())
accuracy = r2_score(freedom_test.values.ravel(), freedom_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.5043064066023448


array([0.12971038, 0.0164357 , 0.07122697, 0.16697197, 0.04759   ,
       0.09775556, 0.02858961, 0.07844687, 0.02004848, 0.08835546,
       0.03016499, 0.12866287, 0.10307935, 0.0530218 , 0.02078125,
       0.08801852, 0.12494685, 0.08100695, 0.08261166, 0.03944286,
       0.00127001, 0.24307577, 0.10196592, 0.0097297 , 0.17858877,
       0.10922669, 0.0913888 , 0.00600355, 0.01656912, 0.10789668,
       0.17186407, 0.06517995, 0.06086164, 0.15099028, 0.06648829,
       0.02726998, 0.01869781, 0.0111131 , 0.05636281, 0.0460797 ,
       0.07322698, 0.01716272, 0.02372929, 0.13104635, 0.0662229 ,
       0.21751108, 0.0798486 , 0.00241328, 0.25020268, 0.04119262,
       0.40045419, 0.12230826, 0.04695128, 0.03947338, 0.12423943,
       0.08528815, 0.06643954, 0.13143389, 0.09454589, 0.08159871,
       0.03106391, 0.01904056, 0.09420831, 0.00832991, 0.00512175,
       0.15240995, 0.03371333, 0.03021404, 0.09678849, 0.26885375,
       0.14976699, 0.14218622, 0.08432687, 0.05853984, 0.01104

In [10]:
# Training the model to predict Trust
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, trust_train.values.ravel())
trust_predictions = rf.predict(df_test)
errors = abs(trust_predictions - trust_test.values.ravel())
accuracy = r2_score(trust_test.values.ravel(), trust_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.6481461496724736


array([0.01930544, 0.09166975, 0.05725885, 0.07055694, 0.03517064,
       0.0918657 , 0.06195448, 0.02650861, 0.01355663, 0.07907099,
       0.00312324, 0.00749659, 0.07064938, 0.05119282, 0.05696776,
       0.03248685, 0.13215335, 0.02724947, 0.01105282, 0.08821999,
       0.00031627, 0.0093371 , 0.02062033, 0.03113979, 0.13281596,
       0.03386482, 0.03161379, 0.05366572, 0.03425438, 0.00588753,
       0.02490855, 0.0520258 , 0.10198081, 0.20044987, 0.02268495,
       0.03564843, 0.02071409, 0.01681718, 0.00475388, 0.12082119,
       0.0120068 , 0.05485227, 0.08899544, 0.11938514, 0.08356373,
       0.06349781, 0.01178869, 0.03802373, 0.02366971, 0.02856234,
       0.11620963, 0.03332633, 0.01295058, 0.05796832, 0.03150051,
       0.01820967, 0.04562056, 0.08156547, 0.02323195, 0.00516489,
       0.00597184, 0.01876739, 0.0066381 , 0.05670439, 0.04138179,
       0.03576272, 0.0512847 , 0.05026557, 0.05412341, 0.12118327,
       0.00547817, 0.04426391, 0.1055087 , 0.05354251, 0.02171

In [11]:
#Training the model to predict Generosity
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, generosity_train.values.ravel())
generosity_predictions = rf.predict(df_test)
errors = abs(generosity_predictions - generosity_test.values.ravel())
accuracy = r2_score(generosity_test.values.ravel(), generosity_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.4903515246787312


array([7.41769482e-02, 3.70270407e-02, 7.43484920e-02, 4.70593249e-02,
       5.53302270e-02, 1.02126827e-01, 1.15454001e-01, 4.37572185e-02,
       8.29928911e-02, 6.54620927e-02, 1.03687140e-01, 1.23864023e-03,
       5.23100401e-02, 3.57508108e-02, 1.57328658e-01, 3.68923890e-03,
       8.82044034e-02, 5.79909054e-02, 4.17548019e-02, 8.47568125e-02,
       3.41834152e-02, 5.25748647e-02, 6.43505239e-02, 2.19528614e-02,
       1.69530774e-01, 6.36086689e-04, 3.55983936e-02, 1.69638382e-01,
       1.63792151e-02, 1.40736423e-02, 3.03148851e-02, 3.74888071e-04,
       1.23105721e-01, 5.50639421e-02, 1.24921931e-02, 9.79064358e-03,
       8.43079494e-02, 1.66935691e-01, 7.66797803e-02, 1.64630824e-03,
       3.66253494e-02, 4.88794545e-02, 9.50131722e-02, 9.36334465e-02,
       6.44244517e-02, 1.76684603e-01, 2.76628217e-03, 3.91414067e-02,
       2.05725083e-01, 4.41715599e-03, 1.44650347e-01, 8.60529855e-02,
       1.02074363e-01, 3.25698985e-01, 2.82524824e-02, 9.35645432e-02,
      

In [12]:
#Training the model to predict Dystopia
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, dystopia_train.values.ravel())
dystopia_predictions = rf.predict(df_test)
errors = abs(dystopia_predictions - dystopia_test.values.ravel())
accuracy = r2_score(dystopia_test.values.ravel(), dystopia_predictions)
print('R2 score: ', accuracy)
errors

R2 score:  -0.019298328281836197


array([0.01141167, 0.5377717 , 0.07025283, 0.54330071, 0.18256523,
       0.49036452, 0.46236894, 0.20063381, 0.26542043, 0.41720043,
       0.43242248, 0.48434361, 0.32544828, 0.15707548, 0.95451589,
       0.15762411, 0.17233003, 1.37447266, 0.07568565, 0.91600981,
       0.13527394, 0.20961937, 0.51415106, 0.11546783, 0.26428843,
       0.10028167, 0.05002884, 0.52821522, 0.26010887, 0.41561395,
       0.43196974, 0.4778802 , 0.16725253, 0.15708576, 1.03412717,
       0.36796417, 0.06357952, 0.4986479 , 0.23375539, 0.05768327,
       0.31594758, 0.32256117, 0.41924364, 0.4454892 , 0.49649892,
       0.52890044, 0.47047204, 0.48495664, 0.7071705 , 0.21886457,
       0.47562762, 0.02211163, 0.64614118, 0.71842136, 0.82805946,
       0.36661534, 0.18399658, 0.5107612 , 0.61012092, 0.90688607,
       0.42209148, 0.42424343, 0.48294402, 0.27894179, 0.59095039,
       0.01843368, 0.48031027, 0.62115227, 0.33696778, 0.03600571,
       0.35656461, 0.57729313, 0.23317678, 0.11881983, 0.49781

In [13]:
#Predicting Score
predictions = economy_predictions + family_predictions + health_predictions + freedom_predictions + trust_predictions + generosity_predictions + dystopia_predictions
errors = abs(predictions - score_test.values.ravel())
accuracy = r2_score(score_test.values.ravel(), predictions)
print('R2 score: ', accuracy)
errors

R2 score:  0.7770247347829655


array([0.39808746, 0.54973007, 0.46269922, 0.56990103, 0.23704051,
       0.58915774, 0.19327388, 0.47001478, 0.06220177, 0.54574308,
       0.56349632, 0.4433641 , 0.81320873, 0.35187956, 0.3138736 ,
       0.17433521, 0.06973895, 0.98596707, 0.46449217, 0.24474996,
       0.4014285 , 0.64833017, 0.13832474, 0.4225466 , 1.41278376,
       0.18411795, 0.30229658, 0.64498259, 0.03469078, 1.07041585,
       0.79376074, 0.45642538, 0.16985798, 0.76881479, 0.42185123,
       0.08636269, 0.02284798, 0.22116071, 0.25492347, 0.49821671,
       0.12218982, 0.19315431, 0.55059497, 0.82597466, 0.22434524,
       0.53977078, 1.26459012, 0.39536304, 0.80917729, 0.18985221,
       1.18088404, 0.77084374, 0.5284455 , 0.07696436, 0.82346431,
       0.28768575, 0.39399846, 0.40397817, 0.12722532, 0.52665623,
       0.10103569, 0.54418935, 0.05961289, 0.0545619 , 0.13733737,
       0.00614031, 0.1484396 , 0.6923436 , 0.13434183, 0.30309601,
       1.06550297, 0.45186805, 0.27060764, 0.6511749 , 0.11394

In [14]:
#Find accuracy
rows = len(predictions)
tp = 0
for i in range(rows):
    if(predictions[i] >= low_score.loc[i, 'Low'] and predictions[i] <= high_score.loc[i, 'High']):
        tp = tp + 1
print('Accuracy: ', tp/rows*100)

Accuracy:  18.3206106870229
