# Random Forest Regressor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [2]:
df = pd.read_pickle('happiness_data.pkl')
df

Country  Year  Score   Economy    Family    Health  \
0             Afghanistan  2015  3.575  0.319820  0.302850  0.303350   
1             Afghanistan  2016  3.360  0.382270  0.110370  0.173440   
2             Afghanistan  2017  3.794  0.401477  0.581543  0.180747   
3                 Albania  2015  4.959  0.878670  0.804340  0.813250   
4                 Albania  2016  4.655  0.955300  0.501630  0.730070   
5                 Albania  2017  4.644  0.996193  0.803685  0.731160   
6                 Algeria  2015  5.605  0.939290  1.077720  0.617660   
7                 Algeria  2016  6.355  1.052660  0.833090  0.618040   
8                 Algeria  2017  5.872  1.091864  1.146217  0.617585   
9                  Angola  2015  4.033  0.757780  0.860400  0.166830   
10                 Angola  2016  3.866  0.847310  0.663660  0.049910   
11                 Angola  2017  3.795  0.858428  1.104412  0.049869   
12              Argentina  2015  6.574  1.053510  1.248230  0.787230   
13              Argentina  2016  6.650  1.151370  1.066120  0.697110   
14              Argentina  2017  6.599  1.185295  1.440451  0.695137   
15                Armenia  2015  4.350  0.768210  0.777110  0.729900   
16                Armenia  2016  4.360  0.860860  0.624770  0.640830   
17                Armenia  2017  4.376  0.900597  1.007484  0.637524   
18              Australia  2015  7.284  1.333580  1.309230  0.931560   
19              Australia  2016  7.313  1.444430  1.104760  0.851200   
20              Australia  2017  7.284  1.484415  1.510042  0.843887   
21                Austria  2015  7.200  1.337230  1.297040  0.890420   
22                Austria  2016  7.119  1.450380  1.083830  0.805650   
23                Austria  2017  7.006  1.487097  1.459945  0.815328   
24             Azerbaijan  2015  5.212  1.023890  0.937930  0.640450   
25             Azerbaijan  2016  5.291  1.123730  0.760420  0.545040   
26             Azerbaijan  2017  5.234  1.153602  1.152400  0.540776   
27                Bahrain  2015  5.960  1.323760  1.216240  0.747160   
28                Bahrain  2016  6.218  1.440240  0.943970  0.656960   
29                Bahrain  2017  6.087  1.488412  1.323110  0.653133   
..                    ...   ...    ...       ...       ...       ...   
363                Uganda  2015  3.931  0.211020  1.132990  0.338610   
364                Uganda  2016  3.739  0.347190  0.909810  0.196250   
365                Uganda  2017  4.081  0.381431  1.129828  0.217633   
366               Ukraine  2015  4.681  0.799070  1.202780  0.673900   
367               Ukraine  2016  4.324  0.872870  1.014130  0.586280   
368               Ukraine  2017  4.096  0.894652  1.394538  0.575904   
369  United Arab Emirates  2015  6.901  1.427270  1.125750  0.809250   
370  United Arab Emirates  2016  6.573  1.573520  0.871140  0.729930   
371  United Arab Emirates  2017  6.648  1.626343  1.266410  0.726798   
372        United Kingdom  2015  6.867  1.266370  1.285480  0.909430   
373        United Kingdom  2016  6.725  1.402830  1.086720  0.809910   
374        United Kingdom  2017  6.714  1.441634  1.496460  0.805336   
375         United States  2015  7.119  1.394510  1.247110  0.861790   
376         United States  2016  7.104  1.507960  1.047820  0.779000   
377         United States  2017  6.993  1.546259  1.419921  0.774287   
378               Uruguay  2015  6.485  1.061660  1.208900  0.811600   
379               Uruguay  2016  6.545  1.181570  1.031430  0.721830   
380               Uruguay  2017  6.454  1.217560  1.412228  0.719217   
381            Uzbekistan  2015  6.003  0.632440  1.340430  0.597720   
382            Uzbekistan  2016  5.987  0.735910  1.168100  0.501630   
383            Uzbekistan  2017  5.971  0.786441  1.548969  0.498273   
384               Vietnam  2015  5.360  0.632160  0.912260  0.746760   
385               Vietnam  2016  5.061  0.740370  0.791170  0.661570   
386               Vietnam  2017  5.074  0.788548  1.277491

In [3]:
years_train = [2015, 2016]
years_test = [2017]
train_features = df.loc[df['Year'].isin(years_train)]
test_features = df.loc[df['Year'].isin(years_test)]
train_features.reset_index(inplace=True, drop=True)
test_features.reset_index(inplace=True, drop=True)

In [4]:
df_train = train_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)
df_test = test_features.drop(columns=['Country','Year','Score','Economy','Family','Health','Freedom','Trust','Generosity','Dystopia'],axis=1)

In [5]:
#Fetching training and test data set
score_train = pd.DataFrame(train_features['Score'])
economy_train = pd.DataFrame(train_features['Economy'])
family_train = pd.DataFrame(train_features['Family'])
health_train = pd.DataFrame(train_features['Health'])
freedom_train = pd.DataFrame(train_features['Freedom'])
trust_train = pd.DataFrame(train_features['Trust'])
generosity_train = pd.DataFrame(train_features['Generosity'])
dystopia_train = pd.DataFrame(train_features['Dystopia'])

score_test = pd.DataFrame(test_features['Score'])
economy_test = pd.DataFrame(test_features['Economy'])
family_test = pd.DataFrame(test_features['Family'])
health_test = pd.DataFrame(test_features['Health'])
freedom_test = pd.DataFrame(test_features['Freedom'])
trust_test = pd.DataFrame(test_features['Trust'])
generosity_test = pd.DataFrame(test_features['Generosity'])
dystopia_test = pd.DataFrame(test_features['Dystopia'])

In [6]:
#Training the model to predict Economy
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, economy_train.values.ravel())
economy_predictions = rf.predict(df_test)
errors = abs(economy_predictions - economy_test.values.ravel())
accuracy = r2_score(economy_test.values.ravel(), economy_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.6762422350344706


array([4.38418728e-01, 6.59679648e-04, 2.51613355e-01, 7.38874469e-02,
       1.38276354e-01, 1.99958168e-02, 7.02480451e-02, 1.50703938e-01,
       1.43680712e-01, 5.02119887e-01, 1.30700852e-01, 1.44907265e-02,
       5.89335310e-01, 3.92339852e-02, 8.60430460e-02, 2.54772960e-02,
       4.12455970e-03, 1.87483001e-01, 1.27296757e-01, 4.17691309e-01,
       1.23058409e-01, 1.25870807e-01, 7.93064880e-02, 1.07646792e-01,
       6.97931601e-01, 1.27095744e-01, 8.11480453e-02, 1.42388026e-01,
       9.50886318e-02, 7.81563449e-02, 1.78833948e-02, 5.60888770e-02,
       3.47962027e-02, 1.46974045e-01, 1.56194162e-01, 6.14599067e-02,
       4.56240434e-03, 4.58677448e-01, 3.84889309e-01, 1.19750972e-01,
       1.00728177e-01, 1.95806609e-01, 6.91363107e-02, 5.25743703e-01,
       6.18791863e-02, 5.05747553e-02, 3.62878270e-01, 3.92448375e-02,
       6.86654835e-02, 8.34304544e-02, 2.46663046e-02, 1.52720617e-01,
       1.54345861e-02, 9.08980627e-02, 1.23309945e-01, 9.19686326e-02,
      

In [7]:
#Training the model to predict Family
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, family_train.values.ravel())
family_predictions = rf.predict(df_test)
errors = abs(family_predictions - family_test.values.ravel())
accuracy = r2_score(family_test.values.ravel(), family_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.6848696028903352


array([0.20931304, 0.02934267, 0.23775856, 0.38400057, 0.36511503,
       0.28890676, 0.37462853, 0.37902862, 0.22000608, 0.35766695,
       0.0755969 , 0.31087086, 0.38546685, 0.10678958, 0.38716386,
       0.30756603, 0.28667737, 0.35988648, 0.40693772, 0.44630347,
       0.43308111, 0.09716798, 0.25318986, 0.31699838, 0.43616241,
       0.26985791, 0.2578164 , 0.24029957, 0.32298011, 0.451086  ,
       0.09719396, 0.08898139, 0.31041442, 0.38741302, 0.45134129,
       0.30666143, 0.25096761, 0.42812236, 0.23910845, 0.32436119,
       0.31326986, 0.35434991, 0.16159292, 0.35481234, 0.28768682,
       0.37768083, 0.38832131, 0.26872801, 0.10110523, 0.23714195,
       0.08447143, 0.49755468, 0.13145308, 0.32653532, 0.09488326,
       0.43107562, 0.27257217, 0.32736969, 0.3901224 , 0.37927718,
       0.27558101, 0.45489694, 0.24193668, 0.40900545, 0.25873905,
       0.37472008, 0.29629983, 0.21330592, 0.42353176, 0.32460929,
       0.41799772, 0.30487263, 0.04812819, 0.33343623, 0.48573

In [8]:
#Training the model to predict Health
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, health_train.values.ravel())
health_predictions = rf.predict(df_test)
errors = abs(health_predictions - family_test.values.ravel())
accuracy = r2_score(health_test.values.ravel(), health_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.8749321689795926


array([0.31005227, 0.06246441, 0.54934545, 0.8564038 , 0.7002995 ,
       0.30607693, 0.67008787, 0.65250724, 0.55266529, 0.62760023,
       0.19497326, 0.66673496, 0.63797536, 0.1182832 , 0.7870374 ,
       0.6915446 , 0.32710803, 0.7255982 , 0.77673911, 0.73395856,
       0.77964066, 0.37287619, 0.4773082 , 0.72837276, 0.67395203,
       0.83096882, 0.46818758, 0.43079038, 0.71635839, 0.63941369,
       0.17937245, 0.29525737, 0.61460884, 0.75179662, 0.80940323,
       0.61156607, 0.50737547, 0.69530527, 0.48054745, 0.66849494,
       0.53057309, 0.89511242, 0.11311407, 0.67980574, 0.56156815,
       0.44594299, 0.68872188, 0.53196308, 0.2993368 , 0.49866005,
       0.48731109, 0.75483908, 0.30653601, 0.70922415, 0.39023841,
       0.70164687, 0.50394001, 0.58132584, 0.73099931, 0.51149101,
       0.61084193, 0.72225589, 0.76446991, 0.46588894, 0.54007372,
       0.63060881, 0.40344234, 0.54454656, 0.71317715, 0.65430131,
       0.62532178, 0.56693591, 0.19111321, 0.59947853, 1.04802

In [9]:
#Training the model to predict Freedom
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, freedom_train.values.ravel())
freedom_predictions = rf.predict(df_test)
errors = abs(freedom_predictions - freedom_test.values.ravel())
accuracy = r2_score(freedom_test.values.ravel(), freedom_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.5004083988163293


array([0.13677941, 0.02478725, 0.05743961, 0.17094521, 0.04181733,
       0.09683744, 0.03408794, 0.08514895, 0.02268814, 0.08331603,
       0.0265904 , 0.13186919, 0.09508733, 0.05128102, 0.02180311,
       0.08180267, 0.11743848, 0.07747391, 0.08159015, 0.04305594,
       0.00043625, 0.22954144, 0.10688167, 0.00344165, 0.17482989,
       0.1062088 , 0.09564615, 0.00591838, 0.01854591, 0.10685914,
       0.17836748, 0.06683586, 0.057503  , 0.14421298, 0.0635713 ,
       0.02405481, 0.0203126 , 0.00671012, 0.04191092, 0.048085  ,
       0.07473588, 0.019765  , 0.02534554, 0.12403917, 0.05966489,
       0.21666638, 0.08173753, 0.0023776 , 0.25734978, 0.04236119,
       0.39673191, 0.12137901, 0.04741426, 0.04230768, 0.13695366,
       0.08285386, 0.06864885, 0.13929662, 0.08098908, 0.08097408,
       0.02803261, 0.02485543, 0.09336589, 0.0157284 , 0.00892402,
       0.15646914, 0.02876923, 0.02904539, 0.10052643, 0.26648633,
       0.14958482, 0.13085834, 0.08177618, 0.05013215, 0.01705

In [10]:
# Training the model to predict Trust
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, trust_train.values.ravel())
trust_predictions = rf.predict(df_test)
errors = abs(trust_predictions - trust_test.values.ravel())
accuracy = r2_score(trust_test.values.ravel(), trust_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.6417219010708366


array([0.01929282, 0.0888565 , 0.06160214, 0.06712551, 0.03319744,
       0.09611235, 0.06595665, 0.02887644, 0.01443583, 0.07251713,
       0.00238809, 0.00076751, 0.07927518, 0.04838877, 0.05882369,
       0.03650717, 0.13782852, 0.0295455 , 0.01741343, 0.08623994,
       0.00135878, 0.01054751, 0.01849234, 0.0292206 , 0.14171746,
       0.03595387, 0.03098645, 0.05641698, 0.03335951, 0.01270918,
       0.02697013, 0.04866626, 0.09552207, 0.20865719, 0.01964122,
       0.0380828 , 0.01810584, 0.0132931 , 0.00509456, 0.12803934,
       0.01637682, 0.04794629, 0.08333224, 0.11611557, 0.09134606,
       0.0630646 , 0.01068701, 0.0438099 , 0.02597603, 0.02758276,
       0.11673703, 0.03172055, 0.01382649, 0.05285696, 0.02974104,
       0.00929363, 0.04707331, 0.08197156, 0.02478753, 0.00432086,
       0.00568426, 0.0234429 , 0.00588033, 0.05656561, 0.03881838,
       0.03048902, 0.04169791, 0.04684608, 0.05891705, 0.1130248 ,
       0.00568192, 0.04027552, 0.10423275, 0.04732241, 0.02186

In [11]:
#Training the model to predict Generosity
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, generosity_train.values.ravel())
generosity_predictions = rf.predict(df_test)
errors = abs(generosity_predictions - generosity_test.values.ravel())
accuracy = r2_score(generosity_test.values.ravel(), generosity_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.4857883746300614


array([7.73029550e-02, 3.93071813e-02, 6.73415094e-02, 3.86511122e-02,
       5.14124344e-02, 1.03407760e-01, 1.10378491e-01, 3.62583844e-02,
       8.72558471e-02, 8.14088792e-02, 9.86361040e-02, 3.31372226e-04,
       4.50122084e-02, 3.06813125e-02, 1.56526967e-01, 4.73755775e-04,
       9.31411976e-02, 5.80927366e-02, 4.07857896e-02, 8.75246330e-02,
       3.28479925e-02, 5.62590001e-02, 6.52124894e-02, 2.06386914e-02,
       1.67756197e-01, 1.98437884e-03, 2.48158789e-02, 1.83106568e-01,
       1.73565450e-02, 1.16216638e-02, 4.07722183e-02, 2.67790238e-04,
       1.20928344e-01, 6.17448296e-02, 8.96850941e-03, 5.11355376e-03,
       8.10170271e-02, 1.71904395e-01, 6.92111968e-02, 2.79307324e-03,
       3.23064878e-02, 4.46178009e-02, 1.00946081e-01, 9.39955417e-02,
       6.43603233e-02, 1.66331708e-01, 3.48137645e-03, 3.73479634e-02,
       1.99237326e-01, 2.25926415e-03, 1.40364626e-01, 9.72606527e-02,
       9.95807595e-02, 3.22558496e-01, 2.45278942e-02, 8.85353760e-02,
      

In [12]:
#Training the model to predict Dystopia
rf = RandomForestRegressor(n_estimators=1000)
rf.fit(df_train, dystopia_train.values.ravel())
dystopia_predictions = rf.predict(df_test)
errors = abs(dystopia_predictions - dystopia_test.values.ravel())
accuracy = r2_score(dystopia_test.values.ravel(), dystopia_predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  -0.02264047757680787


array([0.01338896, 0.55336723, 0.10130777, 0.55259254, 0.16428605,
       0.49455187, 0.4692031 , 0.20002363, 0.26804946, 0.42684989,
       0.46584741, 0.47310985, 0.31235591, 0.16561897, 0.95737635,
       0.14586288, 0.18424584, 1.34978156, 0.12313576, 0.91494698,
       0.12492599, 0.22381703, 0.51837871, 0.13683196, 0.27471218,
       0.09997107, 0.04225585, 0.53304918, 0.26421907, 0.39398926,
       0.41409646, 0.46290229, 0.17574626, 0.17389972, 1.0649163 ,
       0.36811301, 0.05035492, 0.47417539, 0.23589426, 0.04467106,
       0.31608073, 0.31363444, 0.39393176, 0.4095678 , 0.506104  ,
       0.51888122, 0.42978542, 0.48873386, 0.6993855 , 0.22446568,
       0.46042926, 0.00788452, 0.65202234, 0.7461127 , 0.86727399,
       0.38766124, 0.20673591, 0.52101848, 0.61604226, 0.89585422,
       0.4076669 , 0.43706966, 0.52815044, 0.27487125, 0.5767371 ,
       0.00792664, 0.50356128, 0.59990968, 0.37872881, 0.00743034,
       0.37051916, 0.57995914, 0.24239199, 0.10565126, 0.48245

In [13]:
#Predicting Score
predictions = economy_predictions + family_predictions + health_predictions + freedom_predictions + trust_predictions + generosity_predictions + dystopia_predictions
errors = abs(predictions - score_test.values.ravel())
accuracy = r2_score(score_test.values.ravel(), predictions)
print('Accuracy: ', accuracy)
errors

Accuracy:  0.7793166522208855


array([0.41178508, 0.5583431 , 0.54807458, 0.5694038 , 0.25169304,
       0.58545074, 0.18998432, 0.48770751, 0.05850198, 0.46472122,
       0.60242458, 0.42151418, 0.78553801, 0.36783666, 0.30380456,
       0.17044919, 0.10123519, 0.96722402, 0.43092713, 0.25963216,
       0.41793601, 0.65370944, 0.13155974, 0.43045119, 1.3704584 ,
       0.17941881, 0.28332506, 0.6571207 , 0.03081084, 1.03683102,
       0.7812596 , 0.4243268 , 0.16912051, 0.76850797, 0.44019137,
       0.07786955, 0.03829524, 0.17402722, 0.29617613, 0.50997513,
       0.14437776, 0.21977788, 0.56352787, 0.81169794, 0.26375758,
       0.5203043 , 1.2221903 , 0.40275932, 0.81482084, 0.200667  ,
       1.17345364, 0.80742343, 0.53577456, 0.08969602, 0.87826164,
       0.25073101, 0.41110763, 0.41086949, 0.14770141, 0.49829395,
       0.0911507 , 0.52759555, 0.00387013, 0.03550251, 0.1127724 ,
       0.00621742, 0.09491606, 0.68892631, 0.06781923, 0.31630943,
       1.02547235, 0.42916676, 0.31312246, 0.6408678 , 0.12900